# Generated by Django 5.1.2 on 2025-02-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_genre_story_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
